name: Deploy

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          script: |
            cd /var/www/api.lanny.dev
            find . -mindepth 1 ! -name '.env' -exec rm -rf {} +
            git clone https://github.com/Luminate-D/lannydev-api.git
            cp .env lannydev-api/.env
            cd lannydev-api
            yarn install
            yarn build
            pm2 restart lannydevapi || pm2 start dist/main.js --name lannydevapi
